# Generated by Django 2.2.4 on 2022-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
