# Generated by Django 2.2.4 on 2022-04-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_auto_20220403_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(default='notes about this author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default='this book discription'),
        ),
    ]
